#!/usr/bin/env bash
selected=`cat ~/.config/.dotfiles/scripts/tmux-cht-languages ~/.config/.dotfiles/scripts/tmux-cht-utils | fzf`
if [[ -z $selected ]]; then
	exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ~/.config/.dotfiles/scripts/tmux-cht-languages; then
    	query=`echo "$query" | tr " " "+"`
	echo $query
	tmux neww bash -c "curl -s cht.sh/$selected/$query | less"
else
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less"
fi


